[package]
name = "nysm"
version = "0.1.0"
edition = "2021"
description = "Manage secrets from Secrets Providers."
authors = ["Endoze <endoze@endozemedia.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Endoze/nysm"
documentation = "https://docs.rs/nysm"
homepage = "https://github.com/Endoze/nysm"
rust-version = "1.70.0"

[lib]
name = "nysm"

[dependencies]
aws-config = "0.56.1"
aws-sdk-secretsmanager = "0.31.1"
tokio = { version = "1", features = ["full"] }
bat = "0.23.0"
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
clap = { version = "4.4.3", features = ["derive"]}
tabled = "0.14.0"
anyhow = "1"
tempfile = "3"
thiserror = "1.0.48"
async-trait = "0.1.73"

[dev-dependencies]
lazy_static = { version = "1.4.0" }
futures = "0.3.28"
