[package]
name = "nysm"
version = "0.0.0"
edition = "2021"
description = "Manage AWS Secrets"
authors = ["Endoze <endoze@endozemedia.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Endoze/nysm"
documentation = "https://docs.rs/nysm"
homepage = "https://github.com/Endoze/nysm"

[dependencies]
